on:
  pull_request_target:
    types: edited

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: "${{ github.sha }}"
      - run: |
          CR=$( gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/commits/${{ github.sha }}/check-runs |
          jq ".check_suites[].id" )
          
          // WIP
            
