on:
  pull_request:
    types: edited

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.head_ref }}"
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          CR=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/commits/${{ github.head_ref }}/check-runs |
          jq ".check_runs[].id")
          
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/check-runs/${CR}/rerequest
          
