on:
  pull_request:
    types: edited

jobs:
  after-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.head_ref }}"
      - env:
          GH_TOKEN: ${{ secrets.PAT }}
        run: |
          CR=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/commits/${{ github.head_ref }}/check-runs |
          jq '.check_runs[] | select( .name == "job-name" ) | .id' )
          
          echo "${CR}"
          
          curl -s -X POST \
          "https://api.github.com/repos/${{ github.repository }}/check-runs/${CR}/rerequest" \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
          -H "X-GitHub-Api-Version: 2022-11-28"
          
